This is the randomiser function to generate monthly deposit and monthly withdrawal of the bank

```{r}
# Given mean and standard deviation of bank deposit
randomiser <- function(mean_val,std_dev){
  
  # Convert to shape and scale parameters
  shape_param <- (mean_val / std_dev)^2
  scale_param <- (std_dev^2) / mean_val

  # Generate a random variable with the gamma distribution
  randomiser_output <- rgamma(n = 1, shape = shape_param, scale = scale_param)
}

```


Monthly deposit and monthly_deposit update functions
```{r}
# Monthly deposit with year end bonus scenario
month <- 12
monthly_deposit <- randomiser(10000,1000)
monthly_deposit_update <- function(month){
  
  if(month == 12){
  
  monthly_deposit <- randomiser(20000,2000)
  return(monthly_deposit)
  } else {
    return(monthly_deposit)
  } 
}
monthly_deposit_update(month)
```

Monthly_withdrawal_update
```{r}
# Monthly deposit with Chinese new year large withdrawl and Christmas holiday spending scenario
month <- 12
monthly_withdrawal <- randomiser(5000,1000)
monthly_withdrawal_update <- function(month){
  if(month == 2){
    monthly_withdrawal <- randomiser(10000,2000)
    return(monthly_withdrawal)
  } else if(month == 12){
      monthly_withdrawal <- randomiser(10000,2000)
      return(monthly_withdrawal)
  } else{
    return(monthly_withdrawal)
    }
}
monthly_withdrawal_update(month)
```
loan_selection_update function

```{r}
# Create initial loanData dataframe with NA values instead of 0
loanData <- data.frame(loanID = NA, loanType = NA, loanValue = NA, durationToMaturity = NA)

# loan_selection data to add
loan_selection <- data.frame(loanID = c(1), loanType = c(1), loanValue = c(200), durationToMaturity = c(3))

# Define the loan_selection_update function
loan_selection_update <- function(loan_selection, loanData) {
  # Append loan_selection data frame to loanData data frame
  updated_loanData <- rbind(loanData, loan_selection)
  
  return(updated_loanData)
}

# Update loanData with loan_selection using the loan_selection_update function
loanData <- loan_selection_update(loan_selection, loanData)

# Print the updated dataframe
print(loanData)

```

loan_default_update
```{r}
loanData <- data.frame(loanID = c(1,2), loanType = c(1,2), loanValue = c(1000,2000), durationToMaturity = c(2,3), loan_risk = c(0.03,0.05))


loan_default_update <- function() {
  for (i in 1:nrow(loanData)) {
    risk <- loanData$loan_risk[i]/12
    if (runif(1) < risk) {
      loanData$loanValue[i] <- 0
    }
  }
  return(loanData)
}

loan_default_update()
loanData
```


